# -*- coding: utf-8 -*-
"""بيانات تجريبية محدثة للنسخة v16"""

DEMO_MARKET_PLAYERS = [
    {
        "id": 101,
        "web_name": "Duran",
        "full_name": "Jhon Durán",
        "team_id": 7,
        "team_short": "AVL",
        "team_name": "أستون فيلا",
        "pos": "FWD",
        "pos_ar": "مهاجم",
        "price": 6.1,
        "xp": 5.5,
        "xmins": 70,
        "xg_90": 0.78,
        "xa_90": 0.15,
        "selected_by_percent": 6.5,
        "form": 5.2,
        "total_points": 24,
        "status": "a",
        "status_ar": "جاهز يلعب",
        "is_pen_taker": False,
        "is_set_piece": False,
        "can_select": True,
        "diff_next_3": 2.3,
        "next_3": [
            {"opp": "WOL", "side": "(H)", "diff": 2},
            {"opp": "IPS", "side": "(A)", "diff": 2},
            {"opp": "MUN", "side": "(H)", "diff": 3}
        ],
        "last_3_summary": "GW4: 90د، 1هـ [8ن] | GW3: 28د، 1هـ [6ن]"
    },
    {
        "id": 102,
        "web_name": "Calvert-Lewin",
        "full_name": "Dominic Calvert-Lewin",
        "team_id": 11,
        "team_short": "EVE",
        "team_name": "إيفرتون",
        "pos": "FWD",
        "pos_ar": "مهاجم",
        "price": 6.0,
        "xp": 5.2,
        "xmins": 85,
        "xg_90": 0.65,
        "xa_90": 0.12,
        "selected_by_percent": 4.2,
        "form": 4.8,
        "total_points": 22,
        "status": "a",
        "status_ar": "جاهز يلعب",
        "is_pen_taker": True,
        "is_set_piece": False,
        "can_select": True,
        "diff_next_3": 2.3,
        "next_3": [
            {"opp": "LEI", "side": "(A)", "diff": 2},
            {"opp": "CRY", "side": "(H)", "diff": 2},
            {"opp": "NEW", "side": "(H)", "diff": 3}
        ],
        "last_3_summary": "GW4: 85د، 1هـ [8ن] | GW3: 90د، 1هـ، 1أ [12ن]"
    },
    {
        "id": 103,
        "web_name": "Semenyo",
        "full_name": "Antoine Semenyo",
        "team_id": 91,
        "team_short": "BOU",
        "team_name": "بورنموث",
        "pos": "MID",
        "pos_ar": "خط وسط",
        "price": 5.6,
        "xp": 5.0,
        "xmins": 90,
        "xg_90": 0.52,
        "xa_90": 0.22,
        "selected_by_percent": 8.5,
        "form": 5.0,
        "total_points": 25,
        "status": "a",
        "status_ar": "جاهز يلعب",
        "is_pen_taker": False,
        "is_set_piece": True,
        "can_select": True,
        "diff_next_3": 2.7,
        "next_3": [
            {"opp": "LIV", "side": "(A)", "diff": 5},
            {"opp": "SOU", "side": "(H)", "diff": 2},
            {"opp": "LEI", "side": "(A)", "diff": 2}
        ],
        "last_3_summary": "GW4: 90د [3ن] | GW3: 90د، 1هـ [8ن] | GW2: 90د، 1أ [6ن]"
    },
    {
        "id": 104,
        "web_name": "Rogers",
        "full_name": "Morgan Rogers",
        "team_id": 7,
        "team_short": "AVL",
        "team_name": "أستون فيلا",
        "pos": "MID",
        "pos_ar": "خط وسط",
        "price": 5.1,
        "xp": 4.8,
        "xmins": 85,
        "xg_90": 0.35,
        "xa_90": 0.25,
        "selected_by_percent": 9.2,
        "form": 4.2,
        "total_points": 18,
        "status": "a",
        "status_ar": "جاهز يلعب",
        "is_pen_taker": False,
        "is_set_piece": False,
        "can_select": True,
        "diff_next_3": 2.3,
        "next_3": [
            {"opp": "WOL", "side": "(H)", "diff": 2},
            {"opp": "IPS", "side": "(A)", "diff": 2},
            {"opp": "MUN", "side": "(H)", "diff": 3}
        ],
        "last_3_summary": "GW4: 85د [3ن] | GW3: 90د [3ن] | GW2: 90د [2ن]"
    },
    {
        "id": 105,
        "web_name": "Konsa",
        "full_name": "Ezri Konsa",
        "team_id": 7,
        "team_short": "AVL",
        "team_name": "أستون فيلا",
        "pos": "DEF",
        "pos_ar": "مدافع",
        "price": 4.5,
        "xp": 4.6,
        "xmins": 90,
        "xg_90": 0.08,
        "xa_90": 0.05,
        "selected_by_percent": 7.8,
        "form": 4.5,
        "total_points": 19,
        "status": "a",
        "status_ar": "جاهز يلعب",
        "is_pen_taker": False,
        "is_set_piece": False,
        "can_select": True,
        "diff_next_3": 2.3,
        "next_3": [
            {"opp": "WOL", "side": "(H)", "diff": 2},
            {"opp": "IPS", "side": "(A)", "diff": 2},
            {"opp": "MUN", "side": "(H)", "diff": 3}
        ],
        "last_3_summary": "GW4: 90د [2ن] | GW3: 90د، 1هـ [8ن] | GW2: 90د [2ن]"
    },
    {
        "id": 106,
        "web_name": "Lewis",
        "full_name": "Rico Lewis",
        "team_id": 43,
        "team_short": "MCI",
        "team_name": "مانشستر سيتي",
        "pos": "DEF",
        "pos_ar": "مدافع",
        "price": 4.7,
        "xp": 4.5,
        "xmins": 80,
        "xg_90": 0.12,
        "xa_90": 0.28,
        "selected_by_percent": 9.5,
        "form": 4.5,
        "total_points": 21,
        "status": "a",
        "status_ar": "جاهز يلعب",
        "is_pen_taker": False,
        "is_set_piece": False,
        "can_select": True,
        "diff_next_3": 3.0,
        "next_3": [
            {"opp": "ARS", "side": "(H)", "diff": 4},
            {"opp": "NEW", "side": "(A)", "diff": 3},
            {"opp": "FUL", "side": "(H)", "diff": 2}
        ],
        "last_3_summary": "GW4: 90د [2ن] | GW3: 90د، 1أ [5ن] | GW2: 90د [6ن]"
    }
]

DEMO_CHIPS = [{'english_name': 'Wildcard 1',
  'id': 'wildcard_1',
  'is_used': True,
  'name': 'الوايلد كارد (الأولى)',
  'status_label': 'اتلعبت في الجولة 3',
  'used_gw': 3},
 {'english_name': 'Wildcard 2',
  'id': 'wildcard_2',
  'is_used': False,
  'name': 'الوايلد كارد (التانية)',
  'status_label': 'متاحة (من الجولة 20)',
  'used_gw': None},
 {'english_name': 'Free Hit',
  'id': 'freehit',
  'is_used': False,
  'name': 'الفري هيت',
  'status_label': 'متاحة للاستخدام',
  'used_gw': None},
 {'english_name': 'Bench Boost',
  'id': 'bboost',
  'is_used': False,
  'name': 'البنش بوست',
  'status_label': 'متاحة للاستخدام',
  'used_gw': None},
 {'english_name': 'Triple Captain',
  'id': '3xc',
  'is_used': False,
  'name': 'التريبل كابتن',
  'status_label': 'متاحة للاستخدام',
  'used_gw': None}]

DEMO_FIXTURES = [{'away': 'CHE',
  'away_code': 8,
  'away_full': 'تشيلسي',
  'diff_a': 3,
  'diff_h': 4,
  'home': 'WHU',
  'home_code': 21,
  'home_full': 'وست هام',
  'kickoff': '2026-09-19T11:30:00Z'},
 {'away': 'WOL',
  'away_code': 39,
  'away_full': 'ولفرهامبتون',
  'diff_a': 4,
  'diff_h': 2,
  'home': 'AVL',
  'home_code': 7,
  'home_full': 'أستون فيلا',
  'kickoff': '2026-09-19T14:00:00Z'},
 {'away': 'NEW',
  'away_code': 4,
  'away_full': 'نيوكاسل',
  'diff_a': 3,
  'diff_h': 3,
  'home': 'FUL',
  'home_code': 54,
  'home_full': 'فولهام',
  'kickoff': '2026-09-19T14:00:00Z'},
 {'away': 'EVE',
  'away_code': 11,
  'away_full': 'إيفرتون',
  'diff_a': 2,
  'diff_h': 2,
  'home': 'LEI',
  'home_code': 13,
  'home_full': 'ليستر سيتي',
  'kickoff': '2026-09-19T14:00:00Z'},
 {'away': 'BOU',
  'away_code': 91,
  'away_full': 'بورنموث',
  'diff_a': 5,
  'diff_h': 2,
  'home': 'LIV',
  'home_code': 14,
  'home_full': 'ليفربول',
  'kickoff': '2026-09-19T14:00:00Z'},
 {'away': 'IPS',
  'away_code': 40,
  'away_full': 'إيبسويتش',
  'diff_a': 2,
  'diff_h': 2,
  'home': 'SOU',
  'home_code': 20,
  'home_full': 'ساوثهامبتون',
  'kickoff': '2026-09-19T14:00:00Z'},
 {'away': 'BRE',
  'away_code': 94,
  'away_full': 'برينتفورد',
  'diff_a': 4,
  'diff_h': 2,
  'home': 'TOT',
  'home_code': 6,
  'home_full': 'توتنهام',
  'kickoff': '2026-09-19T14:00:00Z'},
 {'away': 'MUN',
  'away_code': 1,
  'away_full': 'مانشستر يونايتد',
  'diff_a': 3,
  'diff_h': 3,
  'home': 'CRY',
  'home_code': 31,
  'home_full': 'كريستال بالاس',
  'kickoff': '2026-09-19T16:30:00Z'},
 {'away': 'NFO',
  'away_code': 17,
  'away_full': 'نوتنجهام فورست',
  'diff_a': 3,
  'diff_h': 2,
  'home': 'BHA',
  'home_code': 36,
  'home_full': 'برايتون',
  'kickoff': '2026-09-20T13:00:00Z'},
 {'away': 'ARS',
  'away_code': 3,
  'away_full': 'أرسنال',
  'diff_a': 4,
  'diff_h': 4,
  'home': 'MCI',
  'home_code': 43,
  'home_full': 'مانشستر سيتي',
  'kickoff': '2026-09-20T15:30:00Z'}]

DEMO_TEAM = {'bench': [{'form': 1.0,
            'id': 12,
            'is_captain': False,
            'is_vice_captain': False,
            'last_3_summary': 'GW2: 0ن (0د)، GW3: 0ن (0د)، GW4: 0ن (0د)',
            'next_3': [{'diff': 3, 'opp': 'CHE', 'side': '(H)'},
                       {'diff': 3, 'opp': 'BRE', 'side': '(A)'},
                       {'diff': 2, 'opp': 'IPS', 'side': '(H)'}],
            'pos': 'GK',
            'price': 4.0,
            'selected_by_percent': 12.0,
            'status': 'a',
            'status_ar': 'دكة احتياط',
            'team_id': 19,
            'team_short': 'WHU',
            'top10k_percent': 1.2,
            'web_name': 'Fabianski',
            'xa_90': 0.0,
            'xg_90': 0.0,
            'xp': 1.5},
           {'form': 5.0,
            'id': 13,
            'is_captain': False,
            'is_vice_captain': False,
            'last_3_summary': 'GW2: 7ن (90د - أسيست)، GW3: 2ن (90د)، GW4: 2ن (90د)',
            'next_3': [{'diff': 3, 'opp': 'NEW', 'side': '(H)'},
                       {'diff': 3, 'opp': 'NFO', 'side': '(A)'},
                       {'diff': 5, 'opp': 'MCI', 'side': '(A)'}],
            'pos': 'DEF',
            'price': 4.7,
            'selected_by_percent': 16.0,
            'status': 'a',
            'status_ar': 'جاهز يلعب',
            'team_id': 9,
            'team_short': 'FUL',
            'top10k_percent': 18.5,
            'web_name': 'Robinson',
            'xa_90': 0.28,
            'xg_90': 0.05,
            'xp': 4.6},
           {'form': 4.2,
            'id': 14,
            'is_captain': False,
            'is_vice_captain': False,
            'last_3_summary': 'GW2: 2ن (70د)، GW3: 1ن (90د)، GW4: 6ن (74د - أسيست)',
            'next_3': [{'diff': 3, 'opp': 'CRY', 'side': '(A)'},
                       {'diff': 3, 'opp': 'TOT', 'side': '(H)'},
                       {'diff': 4, 'opp': 'AVL', 'side': '(A)'}],
            'pos': 'DEF',
            'price': 4.6,
            'selected_by_percent': 14.0,
            'status': 'a',
            'status_ar': 'جاهز يلعب',
            'team_id': 14,
            'team_short': 'MUN',
            'top10k_percent': 12.0,
            'web_name': 'Mazraoui',
            'xa_90': 0.15,
            'xg_90': 0.08,
            'xp': 3.8},
           {'form': 2.8,
            'id': 15,
            'is_captain': False,
            'is_vice_captain': False,
            'last_3_summary': 'GW2: 2ن (90د)، GW3: 2ن (90د)، GW4: 2ن (90د)',
            'next_3': [{'diff': 2, 'opp': 'EVE', 'side': '(H)'},
                       {'diff': 4, 'opp': 'ARS', 'side': '(A)'},
                       {'diff': 2, 'opp': 'BOU', 'side': '(H)'}],
            'pos': 'MID',
            'price': 4.5,
            'selected_by_percent': 8.0,
            'status': 'a',
            'status_ar': 'جاهز يلعب',
            'team_id': 11,
            'team_short': 'LEI',
            'top10k_percent': 0.8,
            'web_name': 'Winks',
            'xa_90': 0.12,
            'xg_90': 0.04,
            'xp': 2.5}],
 'chips': [{'english_name': 'Wildcard 1',
            'id': 'wildcard_1',
            'is_used': True,
            'name': 'الوايلد كارد (الأولى)',
            'status_label': 'اتلعبت في الجولة 3',
            'used_gw': 3},
           {'english_name': 'Wildcard 2',
            'id': 'wildcard_2',
            'is_used': False,
            'name': 'الوايلد كارد (التانية)',
            'status_label': 'متاحة (من الجولة 20)',
            'used_gw': None},
           {'english_name': 'Free Hit',
            'id': 'freehit',
            'is_used': False,
            'name': 'الفري هيت',
            'status_label': 'متاحة للاستخدام',
            'used_gw': None},
           {'english_name': 'Bench Boost',
            'id': 'bboost',
            'is_used': False,
            'name': 'البنش بوست',
            'status_label': 'متاحة للاستخدام',
            'used_gw': None},
           {'english_name': 'Triple Captain',
            'id': '3xc',
            'is_used': False,
            'name': 'التريبل كابتن',
            'status_label': 'متاحة للاستخدام',
            'used_gw': None}],
 'fixtures': [{'away': 'CHE',
               'away_code': 8,
               'away_full': 'تشيلسي',
               'diff_a': 3,
               'diff_h': 4,
               'home': 'WHU',
               'home_code': 21,
               'home_full': 'وست هام',
               'kickoff': '2026-09-19T11:30:00Z'},
              {'away': 'WOL',
               'away_code': 39,
               'away_full': 'ولفرهامبتون',
               'diff_a': 4,
               'diff_h': 2,
               'home': 'AVL',
               'home_code': 7,
               'home_full': 'أستون فيلا',
               'kickoff': '2026-09-19T14:00:00Z'},
              {'away': 'NEW',
               'away_code': 4,
               'away_full': 'نيوكاسل',
               'diff_a': 3,
               'diff_h': 3,
               'home': 'FUL',
               'home_code': 54,
               'home_full': 'فولهام',
               'kickoff': '2026-09-19T14:00:00Z'},
              {'away': 'EVE',
               'away_code': 11,
               'away_full': 'إيفرتون',
               'diff_a': 2,
               'diff_h': 2,
               'home': 'LEI',
               'home_code': 13,
               'home_full': 'ليستر سيتي',
               'kickoff': '2026-09-19T14:00:00Z'},
              {'away': 'BOU',
               'away_code': 91,
               'away_full': 'بورنموث',
               'diff_a': 5,
               'diff_h': 2,
               'home': 'LIV',
               'home_code': 14,
               'home_full': 'ليفربول',
               'kickoff': '2026-09-19T14:00:00Z'},
              {'away': 'IPS',
               'away_code': 40,
               'away_full': 'إيبسويتش',
               'diff_a': 2,
               'diff_h': 2,
               'home': 'SOU',
               'home_code': 20,
               'home_full': 'ساوثهامبتون',
               'kickoff': '2026-09-19T14:00:00Z'},
              {'away': 'BRE',
               'away_code': 94,
               'away_full': 'برينتفورد',
               'diff_a': 4,
               'diff_h': 2,
               'home': 'TOT',
               'home_code': 6,
               'home_full': 'توتنهام',
               'kickoff': '2026-09-19T14:00:00Z'},
              {'away': 'MUN',
               'away_code': 1,
               'away_full': 'مانشستر يونايتد',
               'diff_a': 3,
               'diff_h': 3,
               'home': 'CRY',
               'home_code': 31,
               'home_full': 'كريستال بالاس',
               'kickoff': '2026-09-19T16:30:00Z'},
              {'away': 'NFO',
               'away_code': 17,
               'away_full': 'نوتنجهام فورست',
               'diff_a': 3,
               'diff_h': 2,
               'home': 'BHA',
               'home_code': 36,
               'home_full': 'برايتون',
               'kickoff': '2026-09-20T13:00:00Z'},
              {'away': 'ARS',
               'away_code': 3,
               'away_full': 'أرسنال',
               'diff_a': 4,
               'diff_h': 4,
               'home': 'MCI',
               'home_code': 43,
               'home_full': 'مانشستر سيتي',
               'kickoff': '2026-09-20T15:30:00Z'}],
 'formation': '3-4-3',
 'gameplans': [{'badge': 'أعلى نسبة نجاح',
                'badge_color': 'emerald',
                'bench_gk': 'Fabianski',
                'bench_order': ['Mazraoui', 'Rogers', 'Winks'],
                'captain_reason': 'كبتنة هالاند هي الخيار الأكثر أماناً واستقراراً؛ مواجهته على ملعبه ومعدل نقاطه '
                                  'المتوقعة (9.4ن) هو الأعلى في الجولة، وسجل 8 أهداف في آخر 3 مباريات. صلاح هو النائب '
                                  'كابتن لتأمين الفريق من مباراة أخرى على ملعبه ضد بورنموث.',
                'captain_safe': {'form': 12.0,
                                 'id': 9,
                                 'is_captain': True,
                                 'is_vice_captain': False,
                                 'last_3_summary': 'GW2: 17ن (90د - 3 أهداف)، GW3: 17ن (90د - 3 أهداف)، GW4: 13ن (90د '
                                                   '- هدفين)',
                                 'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                                            {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                                 'pos': 'FWD',
                                 'price': 15.2,
                                 'selected_by_percent': 68.5,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 13,
                                 'team_short': 'MCI',
                                 'top10k_percent': 96.5,
                                 'web_name': 'Haaland',
                                 'xa_90': 0.18,
                                 'xg_90': 1.25,
                                 'xp': 9.4},
                'captain_vice': {'form': 8.5,
                                 'id': 5,
                                 'is_captain': False,
                                 'is_vice_captain': True,
                                 'last_3_summary': 'GW2: 10ن (90د - هدف)، GW3: 17ن (90د - هدفين وأسيست)، GW4: 3ن (90د)',
                                 'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                                            {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                                 'pos': 'MID',
                                 'price': 12.8,
                                 'selected_by_percent': 42.0,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 12,
                                 'team_short': 'LIV',
                                 'top10k_percent': 88.5,
                                 'web_name': 'Salah',
                                 'xa_90': 0.41,
                                 'xg_90': 0.72,
                                 'xp': 8.2},
                'chip_advice': 'وفر شيبساتك دلوقتي! الجولة دي مفيهاش دبل ولا ماتشات متأجلة، فالتريبل كابتن أو الوايلد '
                               'خليهم لأسابيع تانية أتقل.',
                'desc': 'الخيار الأكثر منطقية واستقراراً للجولة. هدفها حصد أعلى معدل نقاط ممكن بدون مخاطرة عشوائية '
                        'لحماية ترتيبك.',
                'differential': {'differential_reason': 'أنت أمام خيارين: إما تنفيذ التبديل الأساسي المقترح، أو اختيار '
                                                        'هذا البديل الاستراتيجي بضم سيمينيو (ملكيته 9.8% فقط) بدلاً من '
                                                        'روجرز للاستفادة من تسديداته الكثيفة على المرمى وجدول بورنموث '
                                                        'الميسر بعد مباراة ليفربول.',
                                 'player': {'form': 5.0,
                                            'id': 202,
                                            'next_3': [{'diff': 4, 'opp': 'LIV', 'side': '(A)'},
                                                       {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                            'pos': 'MID',
                                            'price': 5.6,
                                            'selected_by_percent': 9.8,
                                            'status': 'a',
                                            'status_ar': 'جاهز يلعب',
                                            'team_short': 'BOU',
                                            'web_name': 'Semenyo',
                                            'xa_90': 0.25,
                                            'xg_90': 0.42,
                                            'xp': 5.4},
                                 'replace_who': 'Rogers',
                                 'source': 'market'},
                'expected_pts_range': '70 - 92 نقطة',
                'expected_total_pts': 80.8,
                'extra_insights': ['مراقبة سعر روجرز (Rogers): اللاعب على وشك زيادة سعره (+0.1m) بنهاية الأسبوع نظراً '
                                   'لجدول فيلا الميسر.',
                                   'قمة مانشستر سيتي وأرسنال تجعل نجوم ليفربول وتشيلسي خيارات هجومية بديلة ممتازة هذا '
                                   'الأسبوع.'],
                'final_starters': ['Raya',
                                   'Konaté',
                                   'Gvardiol',
                                   'Alexander-Arnold',
                                   'Robinson',
                                   'Salah',
                                   'Palmer',
                                   'Saka',
                                   'Haaland',
                                   'Watkins',
                                   'Wood'],
                'formation': '3-4-3',
                'lineup_changes': 'بدء Robinson أساسياً بدلاً من Mazraoui نظراً لسهولة مواجهة فولهام على ملعبه أمام '
                                  'نيوكاسل.',
                'lineup_reason': 'بدء Robinson أساسياً بدلاً من Mazraoui نظراً لسهولة مواجهة فولهام على ملعبه أمام '
                                 'نيوكاسل، ودخول كوناتي الوافد الجديد مباشرة في التشكيل الأساسي.',
                'plan_num': 1,
                'title': 'الخطة 1: الخطة المضمونة والآمنة (Safe & Meta)',
                'transfer': {'bank_after': 1.9,
                             'buy': {'form': 5.5,
                                     'id': 201,
                                     'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'}],
                                     'pos': 'DEF',
                                     'price': 5.3,
                                     'selected_by_percent': 8.5,
                                     'status': 'a',
                                     'status_ar': 'جاهز يلعب',
                                     'team_short': 'LIV',
                                     'web_name': 'Konaté',
                                     'xa_90': 0.04,
                                     'xg_90': 0.08,
                                     'xp': 6.4},
                             'cost_diff': -0.7,
                             'gain': 2.2,
                             'sell': {'form': 6.0,
                                      'id': 2,
                                      'is_captain': False,
                                      'is_vice_captain': False,
                                      'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 15ن (90د - هدف)',
                                      'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                                                 {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                                                 {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                      'pos': 'DEF',
                                      'price': 6.0,
                                      'selected_by_percent': 25.0,
                                      'status': 'a',
                                      'status_ar': 'جاهز يلعب',
                                      'team_id': 1,
                                      'team_short': 'ARS',
                                      'top10k_percent': 68.0,
                                      'web_name': 'Gabriel',
                                      'xa_90': 0.04,
                                      'xg_90': 0.12,
                                      'xp': 4.2},
                             'transfer_reason': 'بيع جابرييل (يواجه مانشستر سيتي خارج ملعبه وصعوبة المباراة 4/5) وشراء '
                                                'كوناتي قبل سلسلة الـ 3 مباريات السهلة لليفربول لتوفير £0.7m وزيادة '
                                                'فرص الكلين شيت للأسبوعين القادمين.',
                             'type': 'swap'},
                'why': ['صلاح يلعب في الأنفيلد أمام بورنموث وهو مواجهة سهلة نسبياً (صعوبة 2/5)، وسجله التاريخي أمامهم '
                        'حافل، بينما هالاند يواجه دفاع أرسنال الصلب في قمة تكتيكية صعبة.',
                        'تبديل جابرييل (يواجه مانشستر سيتي خارج ملعبه وصعوبة الماتش 4/5) بكوناتي قبل الـ 3 ماتشات '
                        'السهلة لليفربول هيوفرلك 0.7m ويزيد فرص الكلين شيت للأسبوعين الجايين.',
                        'هالاند يظل صمام الأمان والنائب كابتن الأول لضمان النقط في حال أي مفاجأة.']},
               {'badge': 'للي وراه فارق وعايز يلحق',
                'badge_color': 'orange',
                'bench_gk': 'Fabianski',
                'bench_order': ['Robinson', 'Mazraoui', 'Winks'],
                'captain_reason': 'كبتنة بالمر ضد وست هام خيار ديفرنشال شجاع في خطة الريسك لتعويض فارق النقاط، مع '
                                  'تأمين الفرقة بهالاند كنائب كابتن.',
                'captain_safe': {'form': 7.0,
                                 'id': 6,
                                 'is_captain': False,
                                 'is_vice_captain': False,
                                 'last_3_summary': 'GW2: 17ن (90د - هدف و3 أسيست)، GW3: 5ن (90د)، GW4: 2ن (90د)',
                                 'next_3': [{'diff': 3, 'opp': 'WHU', 'side': '(A)'},
                                            {'diff': 3, 'opp': 'BHA', 'side': '(H)'},
                                            {'diff': 2, 'opp': 'NFO', 'side': '(H)'}],
                                 'pos': 'MID',
                                 'price': 10.6,
                                 'selected_by_percent': 52.0,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 6,
                                 'team_short': 'CHE',
                                 'top10k_percent': 82.0,
                                 'web_name': 'Palmer',
                                 'xa_90': 0.44,
                                 'xg_90': 0.58,
                                 'xp': 7.4},
                'captain_vice': {'form': 12.0,
                                 'id': 9,
                                 'is_captain': True,
                                 'is_vice_captain': False,
                                 'last_3_summary': 'GW2: 17ن (90د - 3 أهداف)، GW3: 17ن (90د - 3 أهداف)، GW4: 13ن (90د '
                                                   '- هدفين)',
                                 'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                                            {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                                 'pos': 'FWD',
                                 'price': 15.2,
                                 'selected_by_percent': 68.5,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 13,
                                 'team_short': 'MCI',
                                 'top10k_percent': 96.5,
                                 'web_name': 'Haaland',
                                 'xa_90': 0.18,
                                 'xg_90': 1.25,
                                 'xp': 9.4},
                'chip_advice': 'لو قلبك ميت ومحتاج ضربة حظ محسوبة، تريبل كابتن على صلاح في الأنفيلد ضد بورنموث واردة '
                               'لو ملكش خلق تستنى جولات الدبل.',
                'desc': 'خطة مصممة لتعويض فارق النقاط في دوري الأصدقاء من خلال خيارات ديفرنشال ذات نسب ملكية منخفضة '
                        'وقدرة تهديفية عالية.',
                'differential': {'differential_reason': 'ورقة هجومية واعدة بملكية 9.8% فقط (أقل من 10%) تمنحك تفوقاً '
                                                        'حاسماً.',
                                 'player': {'form': 5.0,
                                            'id': 202,
                                            'next_3': [{'diff': 4, 'opp': 'LIV', 'side': '(A)'},
                                                       {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                            'pos': 'MID',
                                            'price': 5.6,
                                            'selected_by_percent': 9.8,
                                            'status': 'a',
                                            'status_ar': 'جاهز يلعب',
                                            'team_short': 'BOU',
                                            'web_name': 'Semenyo',
                                            'xa_90': 0.25,
                                            'xg_90': 0.42,
                                            'xp': 5.4},
                                 'replace_who': 'Rogers',
                                 'source': 'market'},
                'expected_pts_range': '66 - 88 نقطة',
                'expected_total_pts': 76.5,
                'extra_insights': ['نسبة كبتنة هالاند ستتجاوز 140% EO هذا الأسبوع؛ التوجه لكبتنة بالمر أو صلاح يمنحك '
                                   'أفضلية كاسحة في حال تعثر السيتي.',
                                   'وست هام يعاني دفاعياً في المساحات العكسية، مما يمنح لاعبي هجوم تشيلسي خطورة '
                                   'عالية.'],
                'final_starters': ['Raya',
                                   'Gabriel',
                                   'Gvardiol',
                                   'Alexander-Arnold',
                                   'Salah',
                                   'Palmer',
                                   'Saka',
                                   'Rogers',
                                   'Haaland',
                                   'Watkins',
                                   'Wood'],
                'formation': '3-4-3',
                'lineup_changes': 'بدء Winks في خط الوسط مع تحويل التشكيل إلى 3-5-2 للاستفادة القصوى من عناصر الوسط '
                                  'الهجومي.',
                'lineup_reason': 'التشكيلة الأساسية متوازنة حالياً، وبدلاء الميدان مرتبون وفقاً لأعلى معدل دقائق ونقاط '
                                 'متوقعة.',
                'plan_num': 2,
                'title': 'الخطة 2: خطة الريسك والديفرنشال (High Risk / High Reward)',
                'transfer': {'bank_after': -0.3,
                             'buy': {'form': 5.5,
                                     'id': 201,
                                     'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'}],
                                     'pos': 'DEF',
                                     'price': 5.3,
                                     'selected_by_percent': 8.5,
                                     'status': 'a',
                                     'status_ar': 'جاهز يلعب',
                                     'team_short': 'LIV',
                                     'web_name': 'Konaté',
                                     'xa_90': 0.04,
                                     'xg_90': 0.08,
                                     'xp': 6.4},
                             'cost_diff': 1.5,
                             'gain': 1.8,
                             'sell': {'form': 6.0,
                                      'id': 2,
                                      'is_captain': False,
                                      'is_vice_captain': False,
                                      'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 15ن (90د - هدف)',
                                      'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                                                 {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                                                 {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                      'pos': 'DEF',
                                      'price': 6.0,
                                      'selected_by_percent': 25.0,
                                      'status': 'a',
                                      'status_ar': 'جاهز يلعب',
                                      'team_id': 1,
                                      'team_short': 'ARS',
                                      'top10k_percent': 68.0,
                                      'web_name': 'Gabriel',
                                      'xa_90': 0.04,
                                      'xg_90': 0.12,
                                      'xp': 4.2},
                             'transfer_reason': 'تبديل استراتيجي لتعزيز توازن التشكيلة والاستفادة من جدول المباريات '
                                                'الميسر.',
                             'type': 'swap'},
                'why': ['كبتنة أولي واتكينز (يملكه 32% بس) ضد دفاع ولفرهامبتون الذي استقبل 11 هدفاً في 4 جولات وماتشه '
                        'في ملعبه هوم؛ لو جاب جونين وصنع هيعمل قفزة صاروخية.',
                        'جاكسون أساسي مع ماريسكا وجدول تشيلسي للـ 3 ماتشات القادمة (وست هام، برايتون، نوتنجهام) مفتوح '
                        'هجومياً ومعدل صناعة الفرص عالي جداً.',
                        'صلاح في الفايس لتأمين أي غياب غير متوقع.']},
               {'badge': 'تكتيك وتوفير فلوس',
                'badge_color': 'blue',
                'bench_gk': 'Fabianski',
                'bench_order': ['Robinson', 'Mazraoui', 'Winks'],
                'captain_reason': 'كبتنة هالاند الخيار الأضمن للجولة مع تأمين صلاح كفايس كابتن.',
                'captain_safe': {'form': 12.0,
                                 'id': 9,
                                 'is_captain': True,
                                 'is_vice_captain': False,
                                 'last_3_summary': 'GW2: 17ن (90د - 3 أهداف)، GW3: 17ن (90د - 3 أهداف)، GW4: 13ن (90د '
                                                   '- هدفين)',
                                 'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                                            {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                                 'pos': 'FWD',
                                 'price': 15.2,
                                 'selected_by_percent': 68.5,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 13,
                                 'team_short': 'MCI',
                                 'top10k_percent': 96.5,
                                 'web_name': 'Haaland',
                                 'xa_90': 0.18,
                                 'xg_90': 1.25,
                                 'xp': 9.4},
                'captain_vice': {'form': 8.5,
                                 'id': 5,
                                 'is_captain': False,
                                 'is_vice_captain': True,
                                 'last_3_summary': 'GW2: 10ن (90د - هدف)، GW3: 17ن (90د - هدفين وأسيست)، GW4: 3ن (90د)',
                                 'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                                            {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                                 'pos': 'MID',
                                 'price': 12.8,
                                 'selected_by_percent': 42.0,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 12,
                                 'team_short': 'LIV',
                                 'top10k_percent': 88.5,
                                 'web_name': 'Salah',
                                 'xa_90': 0.41,
                                 'xg_90': 0.72,
                                 'xp': 8.2},
                'chip_advice': 'إياك تفتح شيب وأنت بتوفر! البنك لما يوصل 4.1m تقدر تعمل أي صفقة سوبر الجولة الجاية من '
                               'غير ما تضرب سالب.',
                'desc': 'استراتيجية مدروسة لتسييل كاش ووضعه في البنك لتمويل صفقات كبرى في الجولات المقبلة دون خصم نقاط '
                        'بسالب.',
                'differential': {'differential_reason': 'ورقة هجومية واعدة بملكية 9.8% فقط (أقل من 10%) تمنحك تفوقاً '
                                                        'حاسماً.',
                                 'player': {'form': 5.0,
                                            'id': 202,
                                            'next_3': [{'diff': 4, 'opp': 'LIV', 'side': '(A)'},
                                                       {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                            'pos': 'MID',
                                            'price': 5.6,
                                            'selected_by_percent': 9.8,
                                            'status': 'a',
                                            'status_ar': 'جاهز يلعب',
                                            'team_short': 'BOU',
                                            'web_name': 'Semenyo',
                                            'xa_90': 0.25,
                                            'xg_90': 0.42,
                                            'xp': 5.4},
                                 'replace_who': 'Rogers',
                                 'source': 'market'},
                'expected_pts_range': '68 - 90 نقطة',
                'expected_total_pts': 78.5,
                'extra_insights': ['توفير السيولة في البنك يمنحك مرونة كاملة للتعاقد مع ساكا أو بالمر في الجولة 6 عند '
                                   'بدء جدولهم السهل.',
                                   'لا تتسرع في شراء لاعبين ارتفعت أسعارهم مؤخراً ما لم تكن هناك استمرارية واضحة في '
                                   'دقائقهم.'],
                'final_starters': ['Raya',
                                   'Gabriel',
                                   'Gvardiol',
                                   'Alexander-Arnold',
                                   'Salah',
                                   'Palmer',
                                   'Saka',
                                   'Rogers',
                                   'Haaland',
                                   'Watkins',
                                   'Wood'],
                'formation': '3-5-2',
                'lineup_changes': 'التشكيلة الأساسية متوازنة حالياً، لا توجد حاجة للتبديل مع مقاعد البدلاء.',
                'lineup_reason': 'التشكيلة الأساسية متوازنة حالياً، وبدلاء الميدان مرتبون وفقاً لأعلى معدل دقائق ونقاط '
                                 'متوقعة.',
                'plan_num': 3,
                'title': 'الخطة 3: خطة الكاش وبناء البنك (Budget & Future Plan)',
                'transfer': {'bank_after': 4.1,
                             'buy': {'form': 5.5,
                                     'id': 201,
                                     'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'}],
                                     'pos': 'DEF',
                                     'price': 5.3,
                                     'selected_by_percent': 8.5,
                                     'status': 'a',
                                     'status_ar': 'جاهز يلعب',
                                     'team_short': 'LIV',
                                     'web_name': 'Konaté',
                                     'xa_90': 0.04,
                                     'xg_90': 0.08,
                                     'xp': 6.4},
                             'cost_diff': -2.9,
                             'gain': -0.2,
                             'sell': {'form': 6.0,
                                      'id': 2,
                                      'is_captain': False,
                                      'is_vice_captain': False,
                                      'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 15ن (90د - هدف)',
                                      'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                                                 {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                                                 {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                      'pos': 'DEF',
                                      'price': 6.0,
                                      'selected_by_percent': 25.0,
                                      'status': 'a',
                                      'status_ar': 'جاهز يلعب',
                                      'team_id': 1,
                                      'team_short': 'ARS',
                                      'top10k_percent': 68.0,
                                      'web_name': 'Gabriel',
                                      'xa_90': 0.04,
                                      'xg_90': 0.12,
                                      'xp': 4.2},
                             'transfer_reason': 'تبديل استراتيجي لتعزيز توازن التشكيلة والاستفادة من جدول المباريات '
                                                'الميسر.',
                             'type': 'swap'},
                'why': ['مبيومو مسدد ركلات الجزاء ويلعب مهاجماً صريحاً في برينتفورد وسعره 7.1m وماتشاته بعد توتنهام '
                        'كلها سهلة.',
                        'هتوفر 2.9m كاش كاملين في البنك مع استمرار تحصيل نقاط متقاربة من المركز.',
                        'هالاند كابتن مضمون وصلاح فايس لتثبيت النقاط.']},
               {'badge': 'تأمين الخط الخلفي',
                'badge_color': 'cyan',
                'bench_gk': 'Fabianski',
                'bench_order': ['Robinson', 'Mazraoui', 'Winks'],
                'captain_reason': 'كبتنة هالاند الخيار الأضمن للجولة مع تأمين صلاح كفايس كابتن.',
                'captain_safe': {'form': 12.0,
                                 'id': 9,
                                 'is_captain': True,
                                 'is_vice_captain': False,
                                 'last_3_summary': 'GW2: 17ن (90د - 3 أهداف)، GW3: 17ن (90د - 3 أهداف)، GW4: 13ن (90د '
                                                   '- هدفين)',
                                 'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                                            {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                                 'pos': 'FWD',
                                 'price': 15.2,
                                 'selected_by_percent': 68.5,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 13,
                                 'team_short': 'MCI',
                                 'top10k_percent': 96.5,
                                 'web_name': 'Haaland',
                                 'xa_90': 0.18,
                                 'xg_90': 1.25,
                                 'xp': 9.4},
                'captain_vice': {'form': 8.5,
                                 'id': 5,
                                 'is_captain': False,
                                 'is_vice_captain': True,
                                 'last_3_summary': 'GW2: 10ن (90د - هدف)، GW3: 17ن (90د - هدفين وأسيست)، GW4: 3ن (90د)',
                                 'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                                            {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                                 'pos': 'MID',
                                 'price': 12.8,
                                 'selected_by_percent': 42.0,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 12,
                                 'team_short': 'LIV',
                                 'top10k_percent': 88.5,
                                 'web_name': 'Salah',
                                 'xa_90': 0.41,
                                 'xg_90': 0.72,
                                 'xp': 8.2},
                'chip_advice': 'لو دكتك كلها أساسية وبتلعب ماتشات سهلة، دي الجولة اللي ممكن تفكر فيها بالبنش بوست لو '
                               'دكة دفاعك ضامنة كلين شيت.',
                'desc': 'التركيز على حصد نقاط مستقرة من خط الدفاع عبر استغلال أعلى احتمالات الكلين شيت والمواجهات '
                        'الدفاعية السهلة.',
                'differential': {'differential_reason': 'ورقة هجومية واعدة بملكية 9.8% فقط (أقل من 10%) تمنحك تفوقاً '
                                                        'حاسماً.',
                                 'player': {'form': 5.0,
                                            'id': 202,
                                            'next_3': [{'diff': 4, 'opp': 'LIV', 'side': '(A)'},
                                                       {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                            'pos': 'MID',
                                            'price': 5.6,
                                            'selected_by_percent': 9.8,
                                            'status': 'a',
                                            'status_ar': 'جاهز يلعب',
                                            'team_short': 'BOU',
                                            'web_name': 'Semenyo',
                                            'xa_90': 0.25,
                                            'xg_90': 0.42,
                                            'xp': 5.4},
                                 'replace_who': 'Rogers',
                                 'source': 'market'},
                'expected_pts_range': '68 - 90 نقطة',
                'expected_total_pts': 78.5,
                'extra_insights': ['تأمين خط الدفاع هو سلاح الفانتازي الصامت؛ نقاط الكلين شيت والبونص الدفاعي تحميك '
                                   'عند صيام المهاجمين.',
                                   'تجنب وضع مدافعين من نفس الفريق في مواجهات الديربي أو المباريات الكبرى خارج الأرض.'],
                'final_starters': ['Raya',
                                   'Gabriel',
                                   'Gvardiol',
                                   'Alexander-Arnold',
                                   'Salah',
                                   'Palmer',
                                   'Saka',
                                   'Rogers',
                                   'Haaland',
                                   'Watkins',
                                   'Wood'],
                'formation': '4-3-3',
                'lineup_changes': 'بدء Mazraoui و Robinson معاً في خط دفاع ثلاثي مع ترينت وجابرييل لتعظيم فرص الخروج '
                                  'بشباك نظيفة.',
                'lineup_reason': 'التشكيلة الأساسية متوازنة حالياً، وبدلاء الميدان مرتبون وفقاً لأعلى معدل دقائق ونقاط '
                                 'متوقعة.',
                'plan_num': 4,
                'title': 'الخطة 4: خطة تأمين الدفاع والكلين شيت (Clean Sheet Hunters)',
                'transfer': {'bank_after': 1.2,
                             'buy': {'form': 5.5,
                                     'id': 201,
                                     'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'}],
                                     'pos': 'DEF',
                                     'price': 5.3,
                                     'selected_by_percent': 8.5,
                                     'status': 'a',
                                     'status_ar': 'جاهز يلعب',
                                     'team_short': 'LIV',
                                     'web_name': 'Konaté',
                                     'xa_90': 0.04,
                                     'xg_90': 0.08,
                                     'xp': 6.4},
                             'cost_diff': 0.0,
                             'gain': 2.0,
                             'sell': {'form': 6.0,
                                      'id': 2,
                                      'is_captain': False,
                                      'is_vice_captain': False,
                                      'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 15ن (90د - هدف)',
                                      'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                                                 {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                                                 {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                      'pos': 'DEF',
                                      'price': 6.0,
                                      'selected_by_percent': 25.0,
                                      'status': 'a',
                                      'status_ar': 'جاهز يلعب',
                                      'team_id': 1,
                                      'team_short': 'ARS',
                                      'top10k_percent': 68.0,
                                      'web_name': 'Gabriel',
                                      'xa_90': 0.04,
                                      'xg_90': 0.12,
                                      'xp': 4.2},
                             'transfer_reason': 'تبديل استراتيجي لتعزيز توازن التشكيلة والاستفادة من جدول المباريات '
                                                'الميسر.',
                             'type': 'swap'},
                'why': ['دفاع ليفربول (ترينت + روبرتسون) فرصة مضاعفة للخروج بشباك نظيفة مع مساهمات هجومية وصناعة أهداف '
                        'من العرضيات.',
                        'مواجهة بورنموث في الأنفيلد تمنح ترينت حرية التحرك في العمق لتقديم أسيستات محققة وبونص كامل.',
                        'الاعتماد على 4 مدافعين يقلل من مخاطر تعثر المهاجمين في قمة السيتي وأرسنال.']},
               {'badge': 'تعديل جذري بـ -4',
                'badge_color': 'purple',
                'bench_gk': 'Fabianski',
                'bench_order': ['Robinson', 'Mazraoui', 'Winks'],
                'captain_reason': 'كبتنة هالاند الخيار الأضمن للجولة مع تأمين صلاح كفايس كابتن.',
                'captain_safe': {'form': 12.0,
                                 'id': 9,
                                 'is_captain': True,
                                 'is_vice_captain': False,
                                 'last_3_summary': 'GW2: 17ن (90د - 3 أهداف)، GW3: 17ن (90د - 3 أهداف)، GW4: 13ن (90د '
                                                   '- هدفين)',
                                 'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                                            {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                                 'pos': 'FWD',
                                 'price': 15.2,
                                 'selected_by_percent': 68.5,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 13,
                                 'team_short': 'MCI',
                                 'top10k_percent': 96.5,
                                 'web_name': 'Haaland',
                                 'xa_90': 0.18,
                                 'xg_90': 1.25,
                                 'xp': 9.4},
                'captain_vice': {'form': 8.5,
                                 'id': 5,
                                 'is_captain': False,
                                 'is_vice_captain': True,
                                 'last_3_summary': 'GW2: 10ن (90د - هدف)، GW3: 17ن (90د - هدفين وأسيست)، GW4: 3ن (90د)',
                                 'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                                            {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                                            {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                                 'pos': 'MID',
                                 'price': 12.8,
                                 'selected_by_percent': 42.0,
                                 'status': 'a',
                                 'status_ar': 'جاهز يلعب',
                                 'team_id': 12,
                                 'team_short': 'LIV',
                                 'top10k_percent': 88.5,
                                 'web_name': 'Salah',
                                 'xa_90': 0.41,
                                 'xg_90': 0.72,
                                 'xp': 8.2},
                'chip_advice': 'لو مش عايز تاخد سالب 4 وعندك 3 إصابات في الفرقة، يبقى ده ميعاد تفعيل كارت الوايلد كارد '
                               '(Wildcard) وتجديد الفرقة من الصفر.',
                'desc': 'تعديل مزدوج حاسم لإعادة التوازن للتشكيلة، والتخلص من نقاط الضعف ونزول الأسعار قبل انطلاق '
                        'الجولة.',
                'differential': {'differential_reason': 'ورقة هجومية واعدة بملكية 9.8% فقط (أقل من 10%) تمنحك تفوقاً '
                                                        'حاسماً.',
                                 'player': {'form': 5.0,
                                            'id': 202,
                                            'next_3': [{'diff': 4, 'opp': 'LIV', 'side': '(A)'},
                                                       {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                            'pos': 'MID',
                                            'price': 5.6,
                                            'selected_by_percent': 9.8,
                                            'status': 'a',
                                            'status_ar': 'جاهز يلعب',
                                            'team_short': 'BOU',
                                            'web_name': 'Semenyo',
                                            'xa_90': 0.25,
                                            'xg_90': 0.42,
                                            'xp': 5.4},
                                 'replace_who': 'Rogers',
                                 'source': 'market'},
                'expected_pts_range': '68 - 90 نقطة',
                'expected_total_pts': 78.5,
                'extra_insights': ['خصم الـ -4 نقاط يتم تعويضه سريعاً إذا كان القادمون الجدد يمتلكون مواجهات سهلة '
                                   'ودقائق 90 دقيقة مضمونة.',
                                   'التخلص السريع من اللاعبين المصابين يمنع تآكل القيمة المالية لتشكيلتك بالسوق.'],
                'final_starters': ['Raya',
                                   'Gabriel',
                                   'Gvardiol',
                                   'Alexander-Arnold',
                                   'Salah',
                                   'Palmer',
                                   'Saka',
                                   'Rogers',
                                   'Haaland',
                                   'Watkins',
                                   'Wood'],
                'formation': '3-4-3',
                'lineup_changes': 'إعادة هيكلة شاملة للتشكيل الأساسي مع وضع البدلاء بالترتيب التكتيكي الأدق تحسباً لأي '
                                  'طارئ.',
                'lineup_reason': 'التشكيلة الأساسية متوازنة حالياً، وبدلاء الميدان مرتبون وفقاً لأعلى معدل دقائق ونقاط '
                                 'متوقعة.',
                'plan_num': 5,
                'title': 'الخطة 5: خطة العملية الجراحية والسالب (Aggressive Overhaul)',
                'transfer': {'buy': {'form': 5.5,
                                     'id': 201,
                                     'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'}],
                                     'pos': 'DEF',
                                     'price': 5.3,
                                     'selected_by_percent': 8.5,
                                     'status': 'a',
                                     'status_ar': 'جاهز يلعب',
                                     'team_short': 'LIV',
                                     'web_name': 'Konaté',
                                     'xa_90': 0.04,
                                     'xg_90': 0.08,
                                     'xp': 6.4},
                             'buy1': {'price': 5.3, 'team_id': 12, 'team_short': 'LIV', 'web_name': 'Konaté'},
                             'buy2': {'price': 7.5, 'team_id': 18, 'team_short': 'TOT', 'web_name': 'Solanke'},
                             'cost_diff': 0.7,
                             'fee_note': 'سالب 4 نقط واحدة بس هتتعوض مباشرة من فارق نقط اللاعبين الجدد (+4.8 ن)',
                             'net_xp_gain': 4.8,
                             'sell': {'form': 6.0,
                                      'id': 2,
                                      'is_captain': False,
                                      'is_vice_captain': False,
                                      'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 15ن (90د - هدف)',
                                      'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                                                 {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                                                 {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                                      'pos': 'DEF',
                                      'price': 6.0,
                                      'selected_by_percent': 25.0,
                                      'status': 'a',
                                      'status_ar': 'جاهز يلعب',
                                      'team_id': 1,
                                      'team_short': 'ARS',
                                      'top10k_percent': 68.0,
                                      'web_name': 'Gabriel',
                                      'xa_90': 0.04,
                                      'xg_90': 0.12,
                                      'xp': 4.2},
                             'sell1': {'price': 6.0,
                                       'selected_by_percent': 25.0,
                                       'team_id': 1,
                                       'team_short': 'ARS',
                                       'web_name': 'Gabriel'},
                             'sell2': {'price': 6.1,
                                       'selected_by_percent': 14.0,
                                       'team_id': 16,
                                       'team_short': 'NFO',
                                       'web_name': 'Wood'},
                             'transfer_reason': 'تبديل استراتيجي لتعزيز توازن التشكيلة والاستفادة من جدول المباريات '
                                                'الميسر.',
                             'type': 'double_swap'},
                'why': ['سولانكي تعافى تماماً من إصابته ومكانه أساسي ومضمون في منظومة توتنهام الهجومية مع بوستيكوجلو '
                        'أمام برينتفولد.',
                        'كوناتي أساسي ثابت مع سلوت في ليفربول وجدول الـ 3 ماتشات القادمة يضمن فارق نقط كبير يغطي '
                        'السالب 4 ويزيد.',
                        'أعلى معدل نقاط متوقعة للجولة (78.2 نقطة) حتى بعد خصم رسوم السالب.']}],
 'manager': {'bank': 1.2,
             'current_gw': 4,
             'free_transfers': 2,
             'gameweek': 5,
             'id': 0,
             'manager_name': 'أحمد كمال',
             'overall_points': 284,
             'overall_rank': 48312,
             'team_name': 'الفراعنة FC',
             'team_value': 111.1},
 'squad_all': [{'form': 5.0,
                'id': 1,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 7ن (90د)',
                'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                           {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                           {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                'pos': 'GK',
                'price': 5.5,
                'selected_by_percent': 28.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 1,
                'team_short': 'ARS',
                'top10k_percent': 42.5,
                'web_name': 'Raya',
                'xa_90': 0.0,
                'xg_90': 0.0,
                'xp': 4.8},
               {'form': 6.0,
                'id': 2,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 15ن (90د - هدف)',
                'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                           {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                           {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                'pos': 'DEF',
                'price': 6.0,
                'selected_by_percent': 25.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 1,
                'team_short': 'ARS',
                'top10k_percent': 68.0,
                'web_name': 'Gabriel',
                'xa_90': 0.04,
                'xg_90': 0.12,
                'xp': 4.2},
               {'form': 4.5,
                'id': 3,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 2ن (90د)، GW3: 2ن (90د)، GW4: 2ن (90د)',
                'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                           {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                           {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                'pos': 'DEF',
                'price': 6.0,
                'selected_by_percent': 28.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 13,
                'team_short': 'MCI',
                'top10k_percent': 35.2,
                'web_name': 'Gvardiol',
                'xa_90': 0.08,
                'xg_90': 0.15,
                'xp': 5.1},
               {'form': 6.5,
                'id': 4,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 8ن (90د)، GW3: 12ن (90د - أسيست)، GW4: 2ن (90د)',
                'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                           {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                           {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                'pos': 'DEF',
                'price': 7.0,
                'selected_by_percent': 31.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 12,
                'team_short': 'LIV',
                'top10k_percent': 72.4,
                'web_name': 'Alexander-Arnold',
                'xa_90': 0.35,
                'xg_90': 0.18,
                'xp': 6.4},
               {'form': 8.5,
                'id': 5,
                'is_captain': False,
                'is_vice_captain': True,
                'last_3_summary': 'GW2: 10ن (90د - هدف)، GW3: 17ن (90د - هدفين وأسيست)، GW4: 3ن (90د)',
                'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                           {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                           {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                'pos': 'MID',
                'price': 12.8,
                'selected_by_percent': 42.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 12,
                'team_short': 'LIV',
                'top10k_percent': 88.5,
                'web_name': 'Salah',
                'xa_90': 0.41,
                'xg_90': 0.72,
                'xp': 8.2},
               {'form': 7.0,
                'id': 6,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 17ن (90د - هدف و3 أسيست)، GW3: 5ن (90د)، GW4: 2ن (90د)',
                'next_3': [{'diff': 3, 'opp': 'WHU', 'side': '(A)'},
                           {'diff': 3, 'opp': 'BHA', 'side': '(H)'},
                           {'diff': 2, 'opp': 'NFO', 'side': '(H)'}],
                'pos': 'MID',
                'price': 10.6,
                'selected_by_percent': 52.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 6,
                'team_short': 'CHE',
                'top10k_percent': 82.0,
                'web_name': 'Palmer',
                'xa_90': 0.44,
                'xg_90': 0.58,
                'xp': 7.4},
               {'form': 6.8,
                'id': 7,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 6ن (90د - أسيست)، GW3: 5ن (90د - أسيست)، GW4: 6ن (90د - أسيست)',
                'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                           {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                           {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                'pos': 'MID',
                'price': 10.0,
                'selected_by_percent': 38.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 1,
                'team_short': 'ARS',
                'top10k_percent': 65.0,
                'web_name': 'Saka',
                'xa_90': 0.38,
                'xg_90': 0.48,
                'xp': 6.8},
               {'form': 4.0,
                'id': 8,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 3ن (90د)، GW3: 2ن (90د)، GW4: 5ن (90د - أسيست)',
                'next_3': [{'diff': 2, 'opp': 'WOL', 'side': '(H)'},
                           {'diff': 2, 'opp': 'IPS', 'side': '(A)'},
                           {'diff': 3, 'opp': 'MUN', 'side': '(H)'}],
                'pos': 'MID',
                'price': 5.1,
                'selected_by_percent': 18.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 2,
                'team_short': 'AVL',
                'top10k_percent': 38.0,
                'web_name': 'Rogers',
                'xa_90': 0.22,
                'xg_90': 0.28,
                'xp': 4.5},
               {'form': 12.0,
                'id': 9,
                'is_captain': True,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 17ن (90د - 3 أهداف)، GW3: 17ن (90د - 3 أهداف)، GW4: 13ن (90د - هدفين)',
                'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                           {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                           {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                'pos': 'FWD',
                'price': 15.2,
                'selected_by_percent': 68.5,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 13,
                'team_short': 'MCI',
                'top10k_percent': 96.5,
                'web_name': 'Haaland',
                'xa_90': 0.18,
                'xg_90': 1.25,
                'xp': 9.4},
               {'form': 6.5,
                'id': 10,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 2ن (65د)، GW3: 5ن (70د - أسيست)، GW4: 13ن (84د - هدفين)',
                'next_3': [{'diff': 2, 'opp': 'WOL', 'side': '(H)'},
                           {'diff': 2, 'opp': 'IPS', 'side': '(A)'},
                           {'diff': 3, 'opp': 'MUN', 'side': '(H)'}],
                'pos': 'FWD',
                'price': 9.0,
                'selected_by_percent': 34.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 2,
                'team_short': 'AVL',
                'top10k_percent': 45.0,
                'web_name': 'Watkins',
                'xa_90': 0.3,
                'xg_90': 0.68,
                'xp': 7.1},
               {'form': 5.5,
                'id': 11,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 2ن (75د)، GW3: 8ن (90د - هدف)، GW4: 2ن (60د)',
                'next_3': [{'diff': 3, 'opp': 'BHA', 'side': '(A)'},
                           {'diff': 2, 'opp': 'FUL', 'side': '(H)'},
                           {'diff': 4, 'opp': 'CHE', 'side': '(A)'}],
                'pos': 'FWD',
                'price': 6.1,
                'selected_by_percent': 14.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 16,
                'team_short': 'NFO',
                'top10k_percent': 22.0,
                'web_name': 'Wood',
                'xa_90': 0.1,
                'xg_90': 0.42,
                'xp': 5.2},
               {'form': 1.0,
                'id': 12,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 0ن (0د)، GW3: 0ن (0د)، GW4: 0ن (0د)',
                'next_3': [{'diff': 3, 'opp': 'CHE', 'side': '(H)'},
                           {'diff': 3, 'opp': 'BRE', 'side': '(A)'},
                           {'diff': 2, 'opp': 'IPS', 'side': '(H)'}],
                'pos': 'GK',
                'price': 4.0,
                'selected_by_percent': 12.0,
                'status': 'a',
                'status_ar': 'دكة احتياط',
                'team_id': 19,
                'team_short': 'WHU',
                'top10k_percent': 1.2,
                'web_name': 'Fabianski',
                'xa_90': 0.0,
                'xg_90': 0.0,
                'xp': 1.5},
               {'form': 5.0,
                'id': 13,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 7ن (90د - أسيست)، GW3: 2ن (90د)، GW4: 2ن (90د)',
                'next_3': [{'diff': 3, 'opp': 'NEW', 'side': '(H)'},
                           {'diff': 3, 'opp': 'NFO', 'side': '(A)'},
                           {'diff': 5, 'opp': 'MCI', 'side': '(A)'}],
                'pos': 'DEF',
                'price': 4.7,
                'selected_by_percent': 16.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 9,
                'team_short': 'FUL',
                'top10k_percent': 18.5,
                'web_name': 'Robinson',
                'xa_90': 0.28,
                'xg_90': 0.05,
                'xp': 4.6},
               {'form': 4.2,
                'id': 14,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 2ن (70د)، GW3: 1ن (90د)، GW4: 6ن (74د - أسيست)',
                'next_3': [{'diff': 3, 'opp': 'CRY', 'side': '(A)'},
                           {'diff': 3, 'opp': 'TOT', 'side': '(H)'},
                           {'diff': 4, 'opp': 'AVL', 'side': '(A)'}],
                'pos': 'DEF',
                'price': 4.6,
                'selected_by_percent': 14.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 14,
                'team_short': 'MUN',
                'top10k_percent': 12.0,
                'web_name': 'Mazraoui',
                'xa_90': 0.15,
                'xg_90': 0.08,
                'xp': 3.8},
               {'form': 2.8,
                'id': 15,
                'is_captain': False,
                'is_vice_captain': False,
                'last_3_summary': 'GW2: 2ن (90د)، GW3: 2ن (90د)، GW4: 2ن (90د)',
                'next_3': [{'diff': 2, 'opp': 'EVE', 'side': '(H)'},
                           {'diff': 4, 'opp': 'ARS', 'side': '(A)'},
                           {'diff': 2, 'opp': 'BOU', 'side': '(H)'}],
                'pos': 'MID',
                'price': 4.5,
                'selected_by_percent': 8.0,
                'status': 'a',
                'status_ar': 'جاهز يلعب',
                'team_id': 11,
                'team_short': 'LEI',
                'top10k_percent': 0.8,
                'web_name': 'Winks',
                'xa_90': 0.12,
                'xg_90': 0.04,
                'xp': 2.5}],
 'starting_11': [{'form': 5.0,
                  'id': 1,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 7ن (90د)',
                  'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                             {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                             {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                  'pos': 'GK',
                  'price': 5.5,
                  'selected_by_percent': 28.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 1,
                  'team_short': 'ARS',
                  'top10k_percent': 42.5,
                  'web_name': 'Raya',
                  'xa_90': 0.0,
                  'xg_90': 0.0,
                  'xp': 4.8},
                 {'form': 6.0,
                  'id': 2,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 6ن (90د)، GW3: 2ن (90د)، GW4: 15ن (90د - هدف)',
                  'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                             {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                             {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                  'pos': 'DEF',
                  'price': 6.0,
                  'selected_by_percent': 25.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 1,
                  'team_short': 'ARS',
                  'top10k_percent': 68.0,
                  'web_name': 'Gabriel',
                  'xa_90': 0.04,
                  'xg_90': 0.12,
                  'xp': 4.2},
                 {'form': 4.5,
                  'id': 3,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 2ن (90د)، GW3: 2ن (90د)، GW4: 2ن (90د)',
                  'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                             {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                             {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                  'pos': 'DEF',
                  'price': 6.0,
                  'selected_by_percent': 28.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 13,
                  'team_short': 'MCI',
                  'top10k_percent': 35.2,
                  'web_name': 'Gvardiol',
                  'xa_90': 0.08,
                  'xg_90': 0.15,
                  'xp': 5.1},
                 {'form': 6.5,
                  'id': 4,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 8ن (90د)، GW3: 12ن (90د - أسيست)، GW4: 2ن (90د)',
                  'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                             {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                             {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                  'pos': 'DEF',
                  'price': 7.0,
                  'selected_by_percent': 31.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 12,
                  'team_short': 'LIV',
                  'top10k_percent': 72.4,
                  'web_name': 'Alexander-Arnold',
                  'xa_90': 0.35,
                  'xg_90': 0.18,
                  'xp': 6.4},
                 {'form': 8.5,
                  'id': 5,
                  'is_captain': False,
                  'is_vice_captain': True,
                  'last_3_summary': 'GW2: 10ن (90د - هدف)، GW3: 17ن (90د - هدفين وأسيست)، GW4: 3ن (90د)',
                  'next_3': [{'diff': 2, 'opp': 'BOU', 'side': '(H)'},
                             {'diff': 2, 'opp': 'WOL', 'side': '(A)'},
                             {'diff': 2, 'opp': 'CRY', 'side': '(A)'}],
                  'pos': 'MID',
                  'price': 12.8,
                  'selected_by_percent': 42.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 12,
                  'team_short': 'LIV',
                  'top10k_percent': 88.5,
                  'web_name': 'Salah',
                  'xa_90': 0.41,
                  'xg_90': 0.72,
                  'xp': 8.2},
                 {'form': 7.0,
                  'id': 6,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 17ن (90د - هدف و3 أسيست)، GW3: 5ن (90د)، GW4: 2ن (90د)',
                  'next_3': [{'diff': 3, 'opp': 'WHU', 'side': '(A)'},
                             {'diff': 3, 'opp': 'BHA', 'side': '(H)'},
                             {'diff': 2, 'opp': 'NFO', 'side': '(H)'}],
                  'pos': 'MID',
                  'price': 10.6,
                  'selected_by_percent': 52.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 6,
                  'team_short': 'CHE',
                  'top10k_percent': 82.0,
                  'web_name': 'Palmer',
                  'xa_90': 0.44,
                  'xg_90': 0.58,
                  'xp': 7.4},
                 {'form': 6.8,
                  'id': 7,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 6ن (90د - أسيست)، GW3: 5ن (90د - أسيست)، GW4: 6ن (90د - أسيست)',
                  'next_3': [{'diff': 4, 'opp': 'MCI', 'side': '(A)'},
                             {'diff': 2, 'opp': 'LEI', 'side': '(H)'},
                             {'diff': 2, 'opp': 'SOU', 'side': '(H)'}],
                  'pos': 'MID',
                  'price': 10.0,
                  'selected_by_percent': 38.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 1,
                  'team_short': 'ARS',
                  'top10k_percent': 65.0,
                  'web_name': 'Saka',
                  'xa_90': 0.38,
                  'xg_90': 0.48,
                  'xp': 6.8},
                 {'form': 4.0,
                  'id': 8,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 3ن (90د)، GW3: 2ن (90د)، GW4: 5ن (90د - أسيست)',
                  'next_3': [{'diff': 2, 'opp': 'WOL', 'side': '(H)'},
                             {'diff': 2, 'opp': 'IPS', 'side': '(A)'},
                             {'diff': 3, 'opp': 'MUN', 'side': '(H)'}],
                  'pos': 'MID',
                  'price': 5.1,
                  'selected_by_percent': 18.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 2,
                  'team_short': 'AVL',
                  'top10k_percent': 38.0,
                  'web_name': 'Rogers',
                  'xa_90': 0.22,
                  'xg_90': 0.28,
                  'xp': 4.5},
                 {'form': 12.0,
                  'id': 9,
                  'is_captain': True,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 17ن (90د - 3 أهداف)، GW3: 17ن (90د - 3 أهداف)، GW4: 13ن (90د - هدفين)',
                  'next_3': [{'diff': 4, 'opp': 'ARS', 'side': '(H)'},
                             {'diff': 3, 'opp': 'NEW', 'side': '(A)'},
                             {'diff': 2, 'opp': 'FUL', 'side': '(H)'}],
                  'pos': 'FWD',
                  'price': 15.2,
                  'selected_by_percent': 68.5,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 13,
                  'team_short': 'MCI',
                  'top10k_percent': 96.5,
                  'web_name': 'Haaland',
                  'xa_90': 0.18,
                  'xg_90': 1.25,
                  'xp': 9.4},
                 {'form': 6.5,
                  'id': 10,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 2ن (65د)، GW3: 5ن (70د - أسيست)، GW4: 13ن (84د - هدفين)',
                  'next_3': [{'diff': 2, 'opp': 'WOL', 'side': '(H)'},
                             {'diff': 2, 'opp': 'IPS', 'side': '(A)'},
                             {'diff': 3, 'opp': 'MUN', 'side': '(H)'}],
                  'pos': 'FWD',
                  'price': 9.0,
                  'selected_by_percent': 34.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 2,
                  'team_short': 'AVL',
                  'top10k_percent': 45.0,
                  'web_name': 'Watkins',
                  'xa_90': 0.3,
                  'xg_90': 0.68,
                  'xp': 7.1},
                 {'form': 5.5,
                  'id': 11,
                  'is_captain': False,
                  'is_vice_captain': False,
                  'last_3_summary': 'GW2: 2ن (75د)، GW3: 8ن (90د - هدف)، GW4: 2ن (60د)',
                  'next_3': [{'diff': 3, 'opp': 'BHA', 'side': '(A)'},
                             {'diff': 2, 'opp': 'FUL', 'side': '(H)'},
                             {'diff': 4, 'opp': 'CHE', 'side': '(A)'}],
                  'pos': 'FWD',
                  'price': 6.1,
                  'selected_by_percent': 14.0,
                  'status': 'a',
                  'status_ar': 'جاهز يلعب',
                  'team_id': 16,
                  'team_short': 'NFO',
                  'top10k_percent': 22.0,
                  'web_name': 'Wood',
                  'xa_90': 0.1,
                  'xg_90': 0.42,
                  'xp': 5.2}]}
